```{r}
# Load the libraries
library(survival)
library(randomForestSRC)
library(ggplot2)
library(pec)
library(dplyr)
library(survivalmodels)
library(survmetrics)
library(reticulate)

# Set default functions for dplyr so we don't accidentally call plyr functions instead
select <- dplyr::select
rename <- dplyr::rename
summarize <- dplyr::summarize
group_by <- dplyr::group_by
## Helper functions
not_all_na <- function(x) any(!is.na(x))
`%notin%` <- Negate(`%in%`)

# Load all survival data
source("../dataLoader.R")

```

```{r}
borrowToRepay <- allSurvivalData %>%
  filter(`Index Event` == "borrow",
         `Outcome Event` == "repay") %>%
  mutate()

borrowToRepay <- borrowToRepay %>%
  select(where(not_all_na))

# Fit Cox Proportional Hazards model
cox_model <- coxph(Surv(timeDiff/86400, status) ~ as.factor(reserve) + as.factor(quarter) + as.factor(coinType) + amountUSD + amount, data = borrowToRepay)

# Summary of Cox model
summary(cox_model)

# Predict survival probabilities
cox_predictions <- predict(cox_model, type = "risk")

# Evaluate model using Concordance Index (C-index)
cox_cindex <- summary(cox_model)$concordance
cat("Cox Model Concordance Index:", cox_cindex[1], "\n")

```

```{r}
dataForRSF <- as.data.frame(unclass(borrowToRepay), stringsAsFactors = TRUE)
  

# Fit Random Survival Forest model
rsf_model <- rfsrc(Surv(timeDiff/86400, status) ~ reserve + quarter + coinType + amountUSD + amount,
                   data = dataForRSF, ntree = 100)

# Summary of RSF model
print(rsf_model)

# Predict survival probabilities
rsf_predictions <- predict(rsf_model)

# Evaluate model using Concordance Index (C-index)
rsf_cindex <- rsf_model$err.rate[nrow(rsf_model$err.rate), "all"]
get.cindex(rf_surv$yvar[,1], rf_surv$yvar[,2], rf_surv$predicted.oob)
cat("Random Survival Forest Concordance Index:", rsf_cindex, "\n")
```

```{r}
deepsurv(formula = Surv(timeDiff/86400, status) ~ reserve + quarter + coinType + amountUSD + amount,
         data = borrowToRepay)
```


```{r}
# Calculate Integrated Brier scores
brier_scores <- pec(
  object = cox_model,
  formula = Surv(timeDiff/86400, status) ~ as.factor(reserve) + as.factor(quarter) + as.factor(coinType) + amountUSD + amount,
  data = borrowToRepay,
  times = seq(5, 25, by = 5) # Define the time points at which to calculate the Brier scores
)
```
