---
title: "DeFi Train/Test split notebooks"
author: "David Quintero $ Charlotte Newman"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
  pdf_document:
    toc: yes
subtitle: "DeFi"
---

## Libraries
```{r}
if (!require("rmarkdown")) {
  install.packages("rmarkdown")
  library(rmarkdown)
}
if (!require("tidyverse")) {
  install.packages("tidyverse")
  library(tidyverse)
}
if (!require("stringr")) {
  install.packages("stringr")
  library(stringr)
}

if (!require("ggbiplot")) {
  install.packages("ggbiplot")
  library(ggbiplot)
}

if (!require("pheatmap")) {
  install.packages("pheatmap")
  library(pheatmap)
}
if(!require("randomForest")) {
  install.packages("randomForest")
  library(randomForest)
}
if(!require("caret")) {
  install.packages("caret")
  library(caret)
}
if(!require("survival")){
  install.packages("survival")
  library(survival)
}
if(!require("survminer")){
  install.packages("survminer")
  library(survminer)
}
if(!require("ggplot2")){
  install.packages("ggplot2")
  library(ggplot2)
}

if(!require("kableExtra")){
  install.packages("kableExtra")
  library(kableExtra)
}
if(!require("rpart")){
  install.packages("rpart")
  library(rpart)
}

if(!require("zoo")){
  install.packages("zoo")
  library(zoo)
}
if(!require("dplyr")){
  install.packages("dplyr")
  library(dplyr)
}

if(!require("forecast")){
  install.packages("forecast")
  library(forecast)
}
```


## Helpful function
```{r}
not_all_na <- function(x) any(!is.na(x))
```

```{r}
transactions <- readRDS("/data/IDEA_DeFi_Research/Data/Lending_Protocols/Aave/V2/Mainnet/Experimental/currentFeatures_DO_NOT_OVERWRITE.rds")
```

## Data Prep:
```{r}

#Load all data:
all_features_raw <- names(transactions)

source("~/DAR-DeFi-LTM-F24/DeFi_source/Data_Creation_Functions/createSurvData.R")

#Borrow to Repay (Feel free to change this to whatever you'd like)
borrowToRepay <- createSurvData("borrow", "repay",
                                data = transactions,
                                subjects = "user",
                                indexCovariates = all_features_raw) %>% select(where(not_all_na)) 


```

```{r}
borrowToRepay <- borrowToRepay %>%
  mutate(quarter = paste0(year(as_datetime(indexTime)), " Q", quarter(as_datetime(indexTime))))

#Convert quarter to Date for date filtering
borrowToRepay <- borrowToRepay %>%
  mutate(quarter_start_date = as.Date(as.yearqtr(quarter, format = "%Y Q%q")))

#Create the end of training and buffer period
end_of_training <- as.Date("2022-06-30")  #End of Q2 2022
buffer_start <- end_of_training + 30  #Start of test data, 30 days after training end

```


## Including Plots
```{r, result01_data}

# Split into training and testing datasets
training_data <- borrowToRepay %>%
                 filter(quarter_start_date <= end_of_training)

testing_data <- borrowToRepay %>%
                filter(quarter_start_date > buffer_start)

```

```{r}
# Save datasets to files
#saveRDS(training_data, "~/DAR-DeFi-LTM-F24/StudentNotebooks/Assignment05/training_data.rds")
#saveRDS(testing_data, "~/DAR-DeFi-LTM-F24/StudentNotebooks/Assignment05/testing_data.rds")

```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
